### ISSUE TITLE
Size option

### ISSUE THREAD

**Issue by schmaxey** [TheSonOfThomp/sketch-flat-export#4]
Hi there,

thanks for this great and useful plugin! I have been always struggling with this. It would be awesome if there is a size option or if the plugin detects the size that has been provided in the "Export" section. Right now the files are being exported in @1x. Options for @2x or @3x would be great.

**Comment by TheSonOfThomp** [comment]
This is a great suggestion. I hope to work on this again soon

**Comment by TheSonOfThomp** [comment]
Hey @schmaxey, I've added a `size` option in version 2.3.0

**Comment by schmaxey** [comment]
@TheSonOfThomp Best news of this week so far! Stay safe and healthy!
